version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
    azure:
        accountname: softrepo
        accountkey: 0ynxf6GZER0O7rkj9MyQtbaMD+9V882t2Bfhn2DiA06Owwkt8YQ+8p1pOeeCg95a5plMPsT5upLL+80O3zGV4g==
        container: dockerimages
http:
    addr: :5000
    secret: laima
    debug:
        addr: localhost:5001
    tls:
        certificate: /go/src/github.com/docker/distribution/certs/domain.crt
        key: /go/src/github.com/docker/distribution/certs/domain.key
redis:
  addr: localhost:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
notifications:
    endpoints:
        - name: local-8082
          url: http://localhost:5003/callback
          headers:
             Authorization: [Bearer <an example token>]
          timeout: 1s
          threshold: 10
          backoff: 1s
          disabled: true
        - name: local-8083
          url: http://localhost:8083/callback
          timeout: 1s
          threshold: 10
          backoff: 1s
          disabled: true
